version: "3.9"

services:
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: calendar
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js
      - mongoDB_dev:/data/db
    networks:
      - network
  
  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - "9090:80"
    volumes:
      - ./docker/nginx/config.dev.conf:/etc/nginx/conf.d/config.dev.conf
      - ./series-calendar-server/files:/app/files
    networks:
      - network

networks:
  network:
    name: network

volumes:
  mongoDB_dev: