version: "3.9"

services:
  mongo:
    container_name: MongoDB
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: calendar
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js
      - ./docker/mongo/data/db:/data/db
    networks:
      - network

  backend:
    container_name: Backend
    build:
      dockerfile: Dockerfile
      context: ./series-calendar-server
    ports:
      - "3000:3000"
    volumes:
      - cdn:/app/files
    depends_on:
      - mongo
    networks:
      - network

front:
  container_name: Frontend
  build:
    dockerfile: Dockerfile
    context: ./series-calendar-frontend
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./docker/nginx/config/conf.d/config.conf:/etc/nginx/conf.d/config.conf
    - ./docker/nginx/config/nginxconfig.io/security.conf:/etc/nginx/nginxconfig.io/security.conf
    - ./docker/nginx/config/nginxconfig.io/general.conf:/etc/nginx/nginxconfig.io/general.conf
    - ./docker/nginx/config/nginxconfig.io/letsencrypt.conf:/etc/nginx/nginxconfig.io/letsencrypt.conf
    - ./docker/nginx/config/nginxconfig.io/proxy.conf:/etc/nginx/nginxconfig.io/proxy.conf
    - /etc/letsencrypt/live:/etc/letsencrypt/live
    - /etc/letsencrypt/archive:/etc/letsencrypt/archive
    - cdn:/app/cdn
  depends_on:
    - backend
  networks:
    - network

networks:
  network:
    name: network

volumes:
  cdn:
